LFDT-web3j/web3j-unit

- README.md
Sample project will not compile without these (and kotlin), so probably worth having that in the README?
> Repo and deps added based on sample project

- build.gradle
- gradle/publish/build.gradle
- src/main/kotlin/org/web3j/container/openethereum/OpenEthereumContainer.kt
Changes OpenEtherum wait strategy to use withMethod("OPTIONS")
> Bumped open containers version to 1.15.1

- README.md
- gradle.properties
- gradle/publish/build.gradle
*required*
*required*
*required*
> Prepare for 4.8.3

- gradle.properties
- src/main/resources/geth/dev.json
Bumped version to 4.8.4
*required*
*required*
*required*
> Changed geth genesis to fix gas issues.

- README.md
- gradle.properties
*required*
*required*
*required*
> Prepare 4.9.1

- README.md
- gradle.properties
*required*
*required*
*required*
> prepare for 4.9.4

- gradle.properties
*required*
*required*
*required*
> bump version to 4.9.5

- README.md
- gradle.properties
*required*
*required*
*required*
> update and bump version

- gradle.properties
Updats to last 4.9.8 Web3j version
*required*
*required*
> update Web3J version

- .github/workflows/build.yml
- .github/workflows/publish-snapshot.yml
- .github/workflows/release.yml
- build.gradle
- gradle.properties
- gradle/jacoco/build.gradle
- gradle/java/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/kotlin/org/web3j/container/embedded/EmbeddedService.kt
Updates to latest web3j version and besu 23.4.0
*required*
*required*
> Update besu 23.4.0

- README.md
- build.gradle
- gradle.properties
*required*
*required*
*required*
> bump version

- build.gradle
*required*
*required*
remove vulnerable version
> Fix logback version

- build.gradle
- gradle.properties
- src/test/kotlin/org/web3j/BesuGreeterTest.kt
- src/test/kotlin/org/web3j/DockerComposeGreeterTest.kt
- src/test/kotlin/org/web3j/EmbeddedGenesisTest.kt
- src/test/kotlin/org/web3j/EmbeddedGreeterTest.kt
- src/test/kotlin/org/web3j/GethGreeterTest.kt
*required*
*required*
*required*
> bump to 4.11.0-SNAPSHOT

- build.gradle
- src/test/kotlin/org/web3j/GethGreeterTest.kt
*required*
*required*
*required*
> Disable geth test

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- MAINTAINERS.md
- SECURITY.md
Files added for repo migration
all
https://toc.hyperledger.org/guidelines/repository-structure.html
> Files added for repo migration

- CHANGELOG.md
- gradle.properties
bump snapshot version to 4.11.2
*required*
*required*
> bump snapshot version to 4.11.2

- CHANGELOG.md
- gradle.properties
bump snapshot version to 4.11.3
*required*
bump snapshot version to 4.11.3
> bump snapshot version to 4.11.3

- CHANGELOG.md
- README.md
- gradle.properties
*required*
*required*
*required*
> Bump snapshot version to 4.11.4

- CHANGELOG.md
- README.md
- gradle.properties
Bump snapshot 4.12.1
*required*
Bump snapshot 4.12.1
> Bump snapshot 4.12.1

- CHANGELOG.md
- README.md
- gradle.properties
*required*
*required*
*required*
> Bump 4.12.1 snapshot

- CHANGELOG.md
- README.md
- gradle.properties
Updates snapshot version to 4.12.3
*required*
*required*
> Bump snapshot 4.12.3

- .github/workflows/release.yml
- CHANGELOG.md
- build.gradle
- gradle/publish/build.gradle
*required*
*required*
*required*
> change org

- .github/workflows/build.yml
- .github/workflows/publish-snapshot.yml
- .github/workflows/release.yml
- CHANGELOG.md
- build.gradle
- gradle/java/build.gradle
- gradle/publish/build.gradle
- src/main/kotlin/org/web3j/container/ServiceBuilder.kt
*required*
*required*
*required*
> upgrade java and besu

- CHANGELOG.md
- build.gradle
*required*
*required*
*required*
> upgrade kotlin due tu pipeline failing issue

- CHANGELOG.md
- MAINTAINERS.md
- README.md
- gradle.properties
- gradle/repositories/build.gradle
*required*
*required*
*required*
> Bump 4.14.1 snap
